#!/usr/bin/python
#
# Copyright 2011 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""chkcrontab - Checks the correctness of crontab files.

Parse crontab files and check each type of line for potential syntax errors.

Basic usage:
  chkcrontab crontab_file
"""

from __future__ import print_function

__author__ = 'lyda@google.com (Kevin Lyda)'

import sys
import chkcrontab_lib as check

from optparse import OptionParser

def main(argv):
  """main program."""
  if len(argv) == 1:
    print('ERROR: No crontab file was specified.')
    sys.exit(1)

  parser = OptionParser()
  parser.add_option('-w', '--whitelist', dest='whitelisted_users', action='append',
                    help='A user to ignore when warning of unrecognized users  This argument may be passed multiple times.')
  parser.add_option('-i', '--ignore_users', dest='ignore_users', action='store_true', default=False,
                    help='If cron files will not have users specified do not try and validate them')
  parser.add_option('-f', '--ignore_filenames', dest='ignore_filenames', action='store_true', default=False,
                    help='Do not validate that the filenames themselves are valid')
  (options, args) = parser.parse_args(argv)

  log = check.LogCounter()
  print('Checking correctness of %s' % argv[1])
  return check.check_crontab(argv[1], log, options.whitelisted_users, ignore_users=options.ignore_users, ignore_filenames=options.ignore_filenames)

if __name__ == '__main__':
  sys.exit(main(sys.argv))
